version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - data-vol:/var/lib/postgresql/data/
      - backup-vol:/backups
    ports:
      - "5432:5432"
volumes:
  data-vol: {}
  backup-vol: {}
