---
- name: Запускаем Nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: started
- name: Перезапускаем Nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: reloaded