---
- name: Установка Nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Меняем конфигурацию Nginx
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Создаем папку для certbot
  become: true
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    mode: 0755

- name: Устанавливаем certbot
  become: true
  apt:
    name:
    - certbot
    - python3-certbot-nginx

- name: Копируем файл настроек certbot
  become: true
  ansible.builtin.copy:
    src: files/cli.ini
    dest: /etc/letsencrypt/cli.ini
    mode: 0644

- name: Запрашиваем сертификаты
  become: true
  ansible.builtin.command: "certbot certonly --test-cert --agree-tos --no-eff-email -q --email sa.pligin@gmail.com -d sapligin.ru -d www.sapligin.ru -d alertmanager.sapligin.ru -d gitlab.sapligin.ru -d grafana.sapligin.ru -d prometheus.sapligin.ru"

- name: Копируем конфиги nginx
  become: true
  template:
    src: "templates/{{ item }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    mode: 0644
  with_items: "{{ nginx_proxy_configs }}"
  notify: Перезапускаем Nginx

#- name: Enable ip_forwarding
#  become: true
#  sysctl:
#    name: net.ipv4.ip_forward
#    value: '1'
#    sysctl_set: yes
#    state: present
#    reload: yes
#
#- name: Enable masquerade NAT
#  become: true
#  iptables:
#    table: nat
#    chain: POSTROUTING
#    out_interface: eth0
#    jump: MASQUERADE