---
- name: Check if GitLab configuration file already exists.
  become: true
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  become: true
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Install GitLab dependencies.
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ gitlab_dependencies }}"

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  become: true
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

- name: Install GitLab
  become: true
  package:
    name: "{{ gitlab_package_name | default(gitlab_edition) }}"
    state: present
  async: 500
  poll: 5
  when: not gitlab_file.stat.exists

- name: Copy GitLab configuration file.
  become: true
  template:
    src: "templates/gitlab.rb.j2"
    dest: "/etc/gitlab/gitlab.rb"
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab